name: portfolio

services:
  react-router:
    build: .
    command: "npm run start"
    expose:
      - "5173"
    ports:
      - "5173:5173"
    init: true
    networks:
      - nginx
    restart: always

networks:
  nginx:
    name: nginx
    external: true
